### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by anri-asaturov** [stoqey/ibkr#4]
Hello, @ceddybi, good man! 
I was just in the beginning of writing a npapi plugin based on TWS c++ client, when I finally found this, and it is so much better.

Did you run this client live? 
Is it somewhat tested and reliable? 
How do you plan to keep it up to date with the official protocol/clients?

I'll def be contributing if I end up using it for my algos.
Thank you!

**Comment by anri-asaturov** [comment]
Alright, I got excited too early, I thought you have implemented the protocol, but this is a wrapper, a good one tho.

**Comment by ceddybi** [comment]
Thank you @anri-asaturov, yes it's a wrapper(based-off [node-ib](https://github.com/pilwon/node-ib)) it makes a socket connection to TWS, no C++/Java library dependency. works great in production

**Comment by anri-asaturov** [comment]
But node-ib hasn't updated in 2 years, you didn't have any issues with that?

**Comment by ceddybi** [comment]
@anri-asaturov, true node-ib has issues, that's why we decided to create a wrapper around it, but we've only been using the most primitive features like orders and market data e.t.c,  there is a list of open issues, it can be great to re-do and update it only requires time but our use-case hasn't faced issues yet, for now

**Comment by ceddybi** [comment]
@anri-asaturov Now we have our own module that we can update anytime, copied the old `node-ib`, added some types and now it's ready https://github.com/stoqey/ib

**Comment by anri-asaturov** [comment]
that's great news @ceddybi
